server:
  port: 9999
spring:
  application:
    name: zmz-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: zmz-client
    api-b:
      path: /api-b/**
      serviceId: zmz-service
