server:
  port: 8888
spring:
  application:
    name: zmz-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhhisabugs/zmz-config
          search-paths:
          username:
          password:
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/