server:
  port: 8761
eureka:
  instance:
    hostname: zmz-eureka
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://zmz-eureka:8761/eureka/
spring:
  profiles: peer2
