server:
  port: 10010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,bus-refresh
spring:
  rabbitmq:
    host: 192.168.199.130
    port: 5672
#    username: mall
#    password: 123456
  zipkin:
    base-url: http://localhost:9411