spring:
  application:
    name: zmz-service
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,bus-refresh
