spring:
  datasource-cluster:
    nodes:
      - name: mainNode
        writeHost: datasource
        readHost: datasource
        isDefault: true
  datasource:
    plantform: mysql
    url: jdbc:mysql://10.17.149.136:3307/zh_test?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: Gyy_2019
    driverClassName: com.mysql.jdbc.Driver
    # 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 25200000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    logAbandoned: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    useGlobalDataSourceStat: true
  druid:
    allow:
    deny:
    loginUsername: admin
    loginPassword: 123456
    resetEnable: true
    #访问路径
    druidUrl: /druid/*
    exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
    monitorPackages: com.tiger.*.service.*,com.tiger.*.service.impl.*,com.tiger.*.mapper.* #GroupId
  # Redis
  cluster:
    redis:
      database: 0
      host: 10.17.149.135
      port: 6379
      password: Gyy_2019
      masterName: cluster6379
      maxTotal: 200
      maxIdle: 50
      numTestsPerEvictionRun: 1024
      maxWaitMillis: 1500
      blockWhenExhausted: false
      type: singleton
      expire: 1800
  mybatis:
    mapperLocations: classpath*:mapper/*Mapper.xml
    typeAliasesPackage:  com.tiger.*.**.model
  messages:
    basename: i18n/messages

